Update 3-redirection

diff --git a/0x0C-web_server/3-redirection b/0x0C-web_server/3-redirection
--- a/0x0C-web_server/3-redirection
+++ b/0x0C-web_server/3-redirection
@@ -14,7 +14,7 @@ sudo ufw allow 'Nginx HTTP'
 REDIRECT_URL="https://github.com/CJ-ONYERO99" 
 
 # Backup the original configuration (optional)
-cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
+sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
 
 # Function to check for existing redirection block
 has_existing_redirect() {
@@ -37,10 +37,10 @@ else
 fi
 
 # Reload Nginx configuration
-service nginx reload
+sudo service nginx reload
 sudo service nginx restart
 
-echo "Redirection configured for /redirect_me to $REDIRECT_URL"
+sudo echo "Redirection configured for /redirect_me to $REDIRECT_URL"
 
 # Verify redirection
-curl -sI 18.235.255.90/redirect_me/ && echo "Redirection seems to be configured correctly." || echo "Redirection might not be working. Check error logs."
+sudo curl -sI 18.235.255.90/redirect_me/ && echo "Redirection seems to be configured correctly." || echo "Redirection might not be working. Check error logs."
